<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */

use App\Apartment;
use Faker\Generator as Faker;

$autoIncrement = autoIncrement();
$factory->define(Apartment::class, function (Faker $faker) use ($autoIncrement) {

    $apartments = [

        // Milano

        [
            'title' => 'Monolocale zona Navigli',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt1.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Torino, 1',
            'city' => 'Milano',
            'country' => 'it',
            'postal_code' => '20022',
            'latitude' => '45.5618', 
            'longitude' => '8.76928', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Porta Venezia - Green Apartment',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt2.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Paolo Sarpi, 2 ',
            'city' => 'Milano',
            'country' => 'it',
            'postal_code' => '20090',
            'latitude' => '45.41628', 
            'longitude' => '9.05123', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => "Sant'Ambrogio & Duomo Functional Studio",
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt3.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Alberto Mario, 6',
            'city' => 'Milano',
            'country' => 'it',
            'postal_code' => '20149',
            'latitude' => '45.47211', 
            'longitude' => '9.15177',            
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Comfortable single bed close to metro',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt4.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Lodovico Scarampo, 5',
            'city' => 'Milano',
            'country' => 'it',
            'postal_code' => '20148',
            'latitude' => '45.48579', 
            'longitude' => '9.14461', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Nuovo ed accogliente Monolocale sui Navigli!',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt5.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Benigno Crespi, 7',
            'city' => 'Milano',
            'country' => 'it',
            'postal_code' => '20159',
            'latitude' => '45.49931', 
            'longitude' => '9.18586', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Mini Abbaino sui tetti di Porta Venezia',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt6.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Cusani, 7',
            'city' => 'Milano',
            'country' => 'it',
            'postal_code' => '20121',
            'latitude' => '45.46861', 
            'longitude' => '9.18407', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Bilocale brevi periodi Niguarda e Isola',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt7.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Giuseppe Giusti, 7',
            'city' => 'Milano',
            'country' => 'it',
            'postal_code' => '20154',
            'latitude' => '45.48029', 
            'longitude' => '9.17834', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Monolocale a Dergano',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt8.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Morazzone, 12',
            'city' => 'Milano',
            'country' => 'it',
            'postal_code' => '20045',
            'latitude' => '45.54572', 
            'longitude' => '9.02234', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Corso Como Garibaldi Room',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt9.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Andrea Massena, 8',
            'city' => 'Milano',
            'country' => 'it',
            'postal_code' => '20145',
            'latitude' => '45.4776', 
            'longitude' => '9.16686', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'BABILA HOSTEL&BISTROT',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt10.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Luca Comerio, 5',
            'city' => 'Milano',
            'country' => 'it',
            'postal_code' => '20145',
            'latitude' => '45.47795', 
            'longitude' => '9.16188', 
            'user_id' => rand(1, 5),
        ],

        // Roma

        [
            'title' => 'B&B Roma Centro - Tripla Superior',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt11.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Capraia, 4',
            'city' => 'Roma',
            'country' => 'it',
            'postal_code' => '00139',
            'latitude' => '41.94651', 
            'longitude' => '12.53373', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Primavera al Colosseo',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt12.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'viale Montemignaio, 34',
            'city' => 'Roma',
            'country' => 'it',
            'postal_code' => '00189',
            'latitude' => '41.9595', 
            'longitude' => '12.45281', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'A Casa di Alessandro Jacuzzi Room',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt13.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Cogoleto, 2',
            'city' => 'Roma',
            'country' => 'it',
            'postal_code' => '00168',
            'latitude' => '41.93061', 
            'longitude' => '12.42261', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Rome Vatican Suite 5',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt14.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Grottaferrata, 5',
            'city' => 'Roma',
            'country' => 'it',
            'postal_code' => '00178',
            'latitude' => '41.86532', 
            'longitude' => '12.53561', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'B&B Rione Monti',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt15.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Viggiano, 21',
            'city' => 'Roma',
            'country' => 'it',
            'postal_code' => '00178',
            'latitude' => '41.83346', 
            'longitude' => '12.51831', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Magenta Luxury Fico 5',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt16.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Vitellia, 3',
            'city' => 'Roma',
            'country' => 'it',
            'postal_code' => '00152',
            'latitude' => '41.88388', 
            'longitude' => '12.45475', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Winkler Suites',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt17.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Chopin, 8',
            'city' => 'Roma',
            'country' => 'it',
            'postal_code' => '00144',
            'latitude' => '41.83426', 
            'longitude' => '12.46864', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'B&B Roma Centro - Matrimoniale Comfort con bagno',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt18.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Galilei, 13',
            'city' => 'Roma',
            'country' => 'it',
            'postal_code' => '00185',
            'latitude' => '41.89031', 
            'longitude' => '12.50359', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Room Deluxe Roma Termini',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt19.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Roccalbegna, 9',
            'city' => 'Roma',
            'country' => 'it',
            'postal_code' => '00148',
            'latitude' => '41.84285', 
            'longitude' =>  '12.42486', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Navona Sweet Home',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt20.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Antoniniana, 16',
            'city' => 'Roma',
            'country' => 'it',
            'postal_code' => '00153',
            'latitude' => '41.87799', 
            'longitude' => '12.49454', 
            'user_id' => rand(1, 5),
        ],

        // Venezia

        [
            'title' => 'Double/Twin Room',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt21.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'calle Fenice, 50',
            'city' => 'Venezia',
            'country' => 'it',
            'postal_code' => '30124',
            'latitude' => '45.43371', 
            'longitude' => '12.33343', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'CÀ LA RIVA mini-apartment',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt22.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'calle di Cristo, 2',
            'city' => 'Venezia',
            'country' => 'it',
            'postal_code' => '30141',
            'latitude' => '45.46048', 
            'longitude' => '12.35449', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Al Teatro Italia centro Venezia',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt23.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'calle Gritti, 14',
            'city' => 'Venezia',
            'country' => 'it',
            'postal_code' => '30141',
            'latitude' => '45.43489', 
            'longitude' => '12.34763', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'DELUXE ROOM IN VENICE CENTRE',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt24.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'calle Pedrocchi, 43',
            'city' => 'Venezia',
            'country' => 'it',
            'postal_code' => '30123',
            'latitude' => '45.43372', 
            'longitude' => '12.32531', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Palazzo DaPonte',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt25.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'calle Squero, 21',
            'city' => 'Venezia',
            'country' => 'it',
            'postal_code' => '30123',
            'latitude' => '45.42976', 
            'longitude' => '12.33445', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Residenza Grisostomo Double Room',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt26.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'calle del Forno, 37',
            'city' => 'Venezia',
            'country' => 'it',
            'postal_code' => '30141',
            'latitude' => '45.45327', 
            'longitude' => '12.35188', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Apartment 2188/A Santacroce',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt27.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'calle Larga Nani, 8',
            'city' => 'Venezia',
            'country' => 'it',
            'postal_code' => '30123',
            'latitude' => '45.43076', 
            'longitude' => '12.32692', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Ca San Piero Biennale',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt28.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'rio Terrà Foscarini, 26',
            'city' => 'Venezia',
            'country' => 'it',
            'postal_code' => '30021',
            'latitude' => '45.60018', 
            'longitude' => '12.88787', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Venice Hotel Altieri',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt29.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'campo della Carità, 16',
            'city' => 'Venezia',
            'country' => 'it',
            'postal_code' => '30126',
            'latitude' => '45.30967', 
            'longitude' => '12.30998', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Ca Tintoretto Room',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt30.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'campiello Traghetto, 6',
            'city' => 'Venezia',
            'country' => 'it',
            'postal_code' => '30125',
            'latitude' => '45.43601', 
            'longitude' => '12.3278', 
            'user_id' => rand(1, 5),
        ],

        // Torino

        [
            'title' => 'MONOLOCALE TORINO CENTRO',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt31.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Lascaris, 60',
            'city' => 'Torino',
            'country' => 'it',
            'postal_code' => '10121',
            'latitude' => '45.06778', 
            'longitude' => '7.67823', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Appartamento Petrarca',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt32.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Confienza, 32',
            'city' => 'Torino',
            'country' => 'it',
            'postal_code' => '10121',
            'latitude' => '45.06857', 
            'longitude' => '7.67557', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Biancas friends',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt33.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Rivarolo, 6',
            'city' => 'Torino',
            'country' => 'it',
            'postal_code' => '10152',
            'latitude' => '45.07959', 
            'longitude' => '7.68706', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Casa Otta',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt34.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Pavia, 80',
            'city' => 'Torino',
            'country' => 'it',
            'postal_code' => '10098',
            'latitude' => '45.0646', 
            'longitude' => '7.55047', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Appartamento Quadrilatero',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt35.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Poliziano, 53',
            'city' => 'Torino',
            'country' => 'it',
            'postal_code' => '10153',
            'latitude' => '45.07654', 
            'longitude' => '7.71662', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Casa Sebastian',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt36.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Fiorano, 2',
            'city' => 'Torino',
            'country' => 'it',
            'postal_code' => '10153',
            'latitude' => '45.06949', 
            'longitude' => '7.70947', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Gretas little home',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt37.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Asti, 13',
            'city' => 'Torino',
            'country' => 'it',
            'postal_code' => '10131',
            'latitude' => '45.06207', 
            'longitude' => '7.70421', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Il Nido di Oreste',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt38.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Sforzesca, 54',
            'city' => 'Torino',
            'country' => 'it',
            'postal_code' => '20006',
            'latitude' => '45.51263', 
            'longitude' => '9.00787', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'La mansarda Bizantina',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt39.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Chisone, 4',
            'city' => 'Torino',
            'country' => 'it',
            'postal_code' => '10128',
            'latitude' => '45.05446', 
            'longitude' => '7.67233', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Open Space Centralissimo',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt40.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Massena, 31',
            'city' => 'Torino',
            'country' => 'it',
            'postal_code' => '10128',
            'latitude' => '45.06023', 
            'longitude' => '7.67241', 
            'user_id' => rand(1, 5),
        ],

        // Firenze

        [
            'title' => 'Il Cuore Di Firenze',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt41.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Lambertesca, 43',
            'city' => 'Firenze',
            'country' => 'it',
            'postal_code' => '50122',
            'latitude' => '43.76867', 
            'longitude' => '11.25487', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'RESIDENZA ALBIZI - Michelangelo',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt42.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via del Fiordaliso, 4',
            'city' => 'Firenze',
            'country' => 'it',
            'postal_code' => '50123',
            'latitude' => '43.76976', 
            'longitude' => '11.25256', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Ponte Vecchio Elegant Apartment',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt43.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Monalda, 3',
            'city' => 'Firenze',
            'country' => 'it',
            'postal_code' => '50123',
            'latitude' => '43.77055', 
            'longitude' => '11.2521', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Delizioso "Studio" in Coverciano',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt44.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via dei Servi, 15',
            'city' => 'Firenze',
            'country' => 'it',
            'postal_code' => '50122',
            'latitude' => '43.77385', 
            'longitude' => '11.25763', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'La Signoria apartament',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt45.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Giuseppe Verdi, 34',
            'city' => 'Firenze',
            'country' => 'it',
            'postal_code' => '50122',
            'latitude' => '43.76957', 
            'longitude' => '11.26107', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Luxury Home Florence',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt46.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Ghibellina, 28',
            'city' => 'Firenze',
            'country' => 'it',
            'postal_code' => '50122',
            'latitude' => '43.76878', 
            'longitude' => '11.26884', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Residenza Sant Anna',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt47.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via dei Benci, 14',
            'city' => 'Firenze',
            'country' => 'it',
            'postal_code' => '50122',
            'latitude' => '43.76739', 
            'longitude' => '11.25935', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Drom Comfort Double Room',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt48.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via dei Brunelleschi, 98',
            'city' => 'Firenze',
            'country' => 'it',
            'postal_code' => '50055',
            'latitude' => '43.77115', 
            'longitude' => '11.10907', 
            'user_id' => rand(1, 5),
        ],

        // Napoli

        [
            'title' => 'Suite Capri',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt49.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Venezia, 6',
            'city' => 'Napoli',
            'country' => 'it',
            'postal_code' => '80142',
            'latitude' => '40.85511', 
            'longitude' => '14.26808', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Suite Amalfi',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt50.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Duomo, 75',
            'city' => 'Napoli',
            'country' => 'it',
            'postal_code' => '80138',
            'latitude' => '40.85558', 
            'longitude' => '14.25707', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Appartamento Ondina',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt51.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Monteoliveto, 23',
            'city' => 'Napoli',
            'country' => 'it',
            'postal_code' => '80134',
            'latitude' => '40.84484', 
            'longitude' => '14.25136', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Toledo Penthouse Don Pedro Apartment',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt52.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Molise, 98',
            'city' => 'Napoli',
            'country' => 'it',
            'postal_code' => '80059',
            'latitude' => '40.77967', 
            'longitude' => '14.38327', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Suite Ischia',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt53.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Vesuvio, 12',
            'city' => 'Napoli',
            'country' => 'it',
            'postal_code' => '80143',
            'latitude' => '40.85746', 
            'longitude' => '14.2922', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Domus Municipio B&B',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt54.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Trentino, 45',
            'city' => 'Napoli',
            'country' => 'it',
            'postal_code' => '80145',
            'latitude' => '40.89041', 
            'longitude' => '14.25877', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'The Little House',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt55.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Marsala, 46',
            'city' => 'Napoli',
            'country' => 'it',
            'postal_code' => '80011',
            'latitude' => '40.93775', 
            'longitude' => '14.36801', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Monolocale a Palazzo Spinelli',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt56.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Saverio Gatto, 55',
            'city' => 'Napoli',
            'country' => 'it',
            'postal_code' => '80131',
            'latitude' => '40.86842', 
            'longitude' => '14.23373', 
            'user_id' => rand(1, 5),
        ],
        
        // Genova

        [
            'title' => 'Attico nel cuore antico di Genova',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt57.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Sierra, 13',
            'city' => 'Genova',
            'country' => 'it',
            'postal_code' => '16122',
            'latitude' => '44.40931', 
            'longitude' => '8.94243', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Camera matrimoniale Blu Mare',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt58.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Colombo, 42',
            'city' => 'Genova',
            'country' => 'it',
            'postal_code' => '16121',
            'latitude' => '44.40598', 
            'longitude' => '8.94455', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'La Casa di Giò',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt59.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Cipro, 65',
            'city' => 'Genova',
            'country' => 'it',
            'postal_code' => '16129',
            'latitude' => '44.40142', 
            'longitude' => '8.94719', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'La porta sul mare',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt60.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Teodosia, 8',
            'city' => 'Genova',
            'country' => 'it',
            'postal_code' => '16129',
            'latitude' => '44.40313', 
            'longitude' => '8.95426', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'La Vecchia Posta di Via Balbi',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt61.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Odessa, 47',
            'city' => 'Genova',
            'country' => 'it',
            'postal_code' => '16129',
            'latitude' => '44.40402', 
            'longitude' => '8.95486', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'The Artists house',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt62.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Gradisca, 28',
            'city' => 'Genova',
            'country' => 'it',
            'postal_code' => '16137',
            'latitude' => '44.41032', 
            'longitude' => '8.95079', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Il Paguro Bernardo',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt63.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Milazzo, 3',
            'city' => 'Genova',
            'country' => 'it',
            'postal_code' => '16128',
            'latitude' => '44.40012', 
            'longitude' => '8.94232', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'La casa del viaggiatore',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt64.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'corso Sardegna, 87',
            'city' => 'Genova',
            'country' => 'it',
            'postal_code' => '16142',
            'latitude' => '44.41091', 
            'longitude' => '8.9542', 
            'user_id' => rand(1, 5),
        ],

        // Palermo

        [
            'title' => 'LeCupole Luxury',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt65.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Cavour, 2',
            'city' => 'Palermo',
            'country' => 'it',
            'postal_code' => '90029',
            'latitude' => '37.74707', 
            'longitude' => '13.82846', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Papillon B&B in the city center',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt66.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Perpignano, 4',
            'city' => 'Palermo',
            'country' => 'it',
            'postal_code' => '90135',
            'latitude' => '38.11943', 
            'longitude' => '13.32819', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Bacche Apartament',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt67.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Oreto, 65',
            'city' => 'Palermo',
            'country' => 'it',
            'postal_code' => '90127',
            'latitude' => '38.10975', 
            'longitude' => '13.36539', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'La casetta di MIRO',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt68.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Villagrazia, 12',
            'city' => 'Palermo',
            'country' => 'it',
            'postal_code' => '90124',
            'latitude' => '38.09811', 
            'longitude' => '13.36971', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Gagini House & Terrace',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt69.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Brasca, 87',
            'city' => 'Palermo',
            'country' => 'it',
            'postal_code' => '90124',
            'latitude' => '38.08689', 
            'longitude' => '13.38159', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'La Rosa dei Venti',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt70.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Ciaculli, 8',
            'city' => 'Palermo',
            'country' => 'it',
            'postal_code' => '90124',
            'latitude' => '38.08663', 
            'longitude' => '13.39176', 
            'user_id' => rand(1, 5),
        ],

        // Bari

        [
            'title' => 'Dreams Room',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt71.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Napoli, 32',
            'city' => 'Bari',
            'country' => 'it',
            'postal_code' => '70010',
            'latitude' => '40.8881', 
            'longitude' => '16.94873', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Macchia Mediterranea - Malva',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt72.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Caldarola, 65',
            'city' => 'Bari',
            'country' => 'it',
            'postal_code' => '70126',
            'latitude' => '41.11707', 
            'longitude' => '16.88283', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'La Casetta Apartment',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt73.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Japigia, 123',
            'city' => 'Bari',
            'country' => 'it',
            'postal_code' => '70126',
            'latitude' => '41.1168', 
            'longitude' => '16.88881', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'CASA RANIERI- centro storico Bari',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt74.jpg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Luigi Einaudi, 78',
            'city' => 'Bari',
            'country' => 'it',
            'postal_code' => '70027',
            'latitude' => '41.05415', 
            'longitude' => '16.70621', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'The House of Arts',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt75.jpeg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Spagna, 3',
            'city' => 'Bari',
            'country' => 'it',
            'postal_code' => '70126',
            'latitude' => '41.1003', 
            'longitude' => '16.93932', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Desire Home',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt76.jpeg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Pola, 75',
            'city' => 'Bari',
            'country' => 'it',
            'postal_code' => '70131',
            'latitude' => '41.07419', 
            'longitude' => '16.86885', 
            'user_id' => rand(1, 5),
        ],

        // Bologna

        [
            'title' => 'Residenza Il Glicine Da Vanni',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt77.jpeg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Imerio, 13',
            'city' => 'Bologna',
            'country' => 'it',
            'postal_code' => '42020',
            'latitude' => '44.63229', 
            'longitude' => '10.53862', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'B&B Allegra Stazione Centrale',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt78.jpeg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Castiglione, 63',
            'city' => 'Bologna',
            'country' => 'it',
            'postal_code' => '40124',
            'latitude' => '44.49286', 
            'longitude' => '11.34647', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Casina Barberia',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt79.jpeg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Tolmino, 87',
            'city' => 'Bologna',
            'country' => 'it',
            'postal_code' => '40134',
            'latitude' => '44.49729', 
            'longitude' => '11.31762', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'La casa dei libri',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt80.jpeg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Oslavia, 2',
            'city' => 'Bologna',
            'country' => 'it',
            'postal_code' => '40133',
            'latitude' => '44.50439', 
            'longitude' => '11.31106', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'Open Space apartment',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt81.jpeg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Benazza, 6',
            'city' => 'Bologna',
            'country' => 'it',
            'postal_code' => '40131',
            'latitude' => '44.53066', 
            'longitude' => '11.32299', 
            'user_id' => rand(1, 5),
        ],
        [
            'title' => 'La Suite Monolocale',
            'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
            'cover_image' => 'apt82.jpeg',
            'rooms_number' => rand(1, 5),
            'beds_number' => rand(1, 5),
            'bathrooms_number' => rand(1, 5),
            'area' => rand(70, 300),
            'address' => 'via Stendhal, 54',
            'city' => 'Bologna',
            'country' => 'it',
            'postal_code' => '40128',
            'latitude' => '44.53321', 
            'longitude' => '11.35486', 
            'user_id' => rand(1, 5),
        ],
    ];

    $autoIncrement -> next();
    $index = $autoIncrement -> current();

    $apartment = $apartments[$index];

    return [
        'title' => $apartment['title'],
        'description' => $apartment['description'],
        'cover_image' => $apartment['cover_image'],
        'rooms_number' => $apartment['rooms_number'],
        'beds_number' => $apartment['beds_number'],
        'bathrooms_number' => $apartment['bathrooms_number'],
        'area' => $apartment['area'],
        'address' =>  $apartment['address'],
        'city' => $apartment['city'],
        'country' => $apartment['country'],
        'postal_code' => $apartment['postal_code'],
        'latitude' => $apartment['latitude'],
        'longitude' => $apartment['longitude'],
        'user_id' => $apartment['user_id'],
    ];
});

function autoIncrement() {
    for ($i = -1; $i < 82; $i++) {
         yield $i;
     }
 } 
